name: Publish to Pages
on: 
  push:
    branches: [master]

jobs:

  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.2
      - name: Docker-Compose Publish
        uses: pennsignals/publish_docker-compose@v0.1.1
        with: 
          docker_compose: docker-compose.yaml
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
